query collectionByHandle($handle: String!) {
  collectionByHandle(handle: $handle) {
    title
    descriptionHtml
    image {
      originalSrc
    },
    products(first: 100) {
      edges {
        node {
          title
          handle
          tags
          images(first: 100) {
            edges {
              node {
                altText
                originalSrc
              }
            }
          }
          presentmentPriceRanges(first: 100) {
            edges {
              node {
                price: minVariantPrice {
                  amount
                  currencyCode
                }
              }
            }
          }
        }
      }
    }
  }
}