query productsByTag($query: String!) {
  products(query: $query, first: 100) {
    edges {
      node {
        id
        title
        descriptionHtml
        handle
        tags
        images(first: 100) {
          edges {
            node {
              altText
              transformedSrc(maxWidth: 650)
            }
          }
        }
        variants(first: 100) {
          edges {
            node {
              id
              title
              available
              selectedOptions {
                name
                value
              }
              presentmentPrices(first: 100) {
                edges {
                  node {
                    compareAtPrice {
                      amount
                      currencyCode
                    }
                    price {
                      amount
                      currencyCode
                    }
                  }
                }
              }
            }
          }
        }
        options {
          id
          name
          values
        }
      }
    }
  }
}