query productByHandle($handle: String!) {
  productByHandle(handle: $handle) {
    title
    descriptionHtml
    images(first: 100) {
      edges {
        node {
          altText
          transformedSrc(maxWidth: 650)
        }
      }
    }
    variants(first: 100) {
      edges {
        node {
          id
          title
          available
          selectedOptions {
            name
            value
          }
          presentmentPrices(first: 100) {
            edges {
              node {
                compareAtPrice {
                  amount
                  currencyCode
                }
                price {
                  amount
                  currencyCode
                }
              }
            }
          }
        }
      }
    }
    options {
      id
      name
      values
    }
  }
}